database:
  user: root
  password: root
  net: tcp
  addr: database:3306
  dbname: golang_trainning
  allowNativePasswords: true
  params:
    parseTime: "true"

server:
  address: 8080

storage:
  endpoint: http://minio:9000
  accessKeyID: minioadmin
  secretAccessKey: minioadmin
  useSSL: false
  buckets:
    womanImage: woman-images
    blogImage: blog-images
